config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tags
  resources :taggings
  resources :comments
  resources :posts
  resources :articles

  match '/login', to: 'users#login', via: [:get, :post]
  match '/logout', to: 'users#logout', via: :get
  root 'posts#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, as: :commentable
  has_many :taggings, as: :tagable
  has_many :tags, through: :taggings
  belongs_to :user
  belongs_to :post

  def do_tags(tag_ids)
    return if tag_ids.blank?
    tags.delete_all
    Tag.where(id: tag_ids).each do |tag|
      Tagging.find_or_create_by(tagable_id: id, tagable_type: 'Article', tag_id: tag.id)
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  belongs_to :user

  def as_json
  	{
  		name: user.name,
  		body: body,
  		id: id
  	}
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, as: :commentable
  has_many :taggings, as: :tagable
  has_many :tags, through: :taggings
  belongs_to :user
  has_many :articles

  def do_tags(tag_ids)
    return if tag_ids.blank?
    tags.delete_all
    Tag.where(id: tag_ids).each do |tag|
      Tagging.find_or_create_by(tagable_id: id, tagable_type: 'Post', tag_id: tag.id)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tagable, :polymorphic => true
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, presence: true
  validates :email, uniqueness: {message: 'Email地址不能重复'}

  has_one :post
  has_many :articles

  attr_accessor :password, :password_confirmation
 
  before_save :encrypt_password

  def self.authenticate(email, password)
    user = self.find_by(email: email)
    if user && user.hashed_password == BCrypt::Engine.hash_secret(password, user.salt)
      return user
    else
      return false
    end
  end

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt if self.salt.blank?
      self.hashed_password = BCrypt::Engine.hash_secret(password, self.salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    return nil unless session[:user_id].present?
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def ensure_sigin_in!
    return if current_user.present?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :ensure_sigin_in!
	def index
		@articles = Article.includes(:tags).where(user_id: current_user.id).page(params[:page]).per(20).order('id desc')
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			@article.do_tags(params[:tag_ids])
			redirect_to articles_path
		else
			render :new
		end
	end
	
	def edit
		@article = Article.find_by_id params[:id]
	end

	def update
		@article = Article.find_by_id params[:id]
		if @article.update_attributes(article_params)
			@article.do_tags(params[:tag_ids])
			redirect_to articles_path
		else
			render :eidt
		end
	end

	def show
		@article = Article.find_by_id params[:id]
		@comments = @article.comments.includes(:user).page(params[:page]).per(5).order('id DESC')
	end

	private
		def article_params
			params.require(:article).permit(:title, :body)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :ensure_sigin_in!

	def create
		commentable = params[:commentable_type].constantize.find_by_id(params[:commentable_id])
		render json: {code: 'error', msg: '纪录不存在，不能评论 '} and return if commentable.nil?
		comment = Comment.new(comment_params)
		comment.commentable = commentable
		comment.user_id = current_user.id
		if comment.save
			render json: {code: 'success', msg: '评论成功', data: comment.as_json}
		else
			render json: {code: 'error', msg: '评论失败'}
		end
	end

	private
		def comment_params
			params.require(:comment).permit(:body)
		end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :ensure_sigin_in!
	def index
		@posts = Post.includes(:comments).page(params[:page]).per(20)
	end
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			@post.do_tags(params[:tag_ids])
			redirect_to posts_path
		else
			render :new
		end
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find_by_id params[:id]
	end

	def update
		@post = Post.find_by_id params[:id]
		if @post.update_attributes(post_params)
			@post.do_tags(params[:tag_ids])
			redirect_to posts_path
		else
			render :edit
		end
	end

	def show
		@post = Post.find_by_id params[:id]
		@comments = @post.comments.includes(:user).page(params[:page]).per(5).order('id desc')
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name = @user.email.split('@')[0] if @user.email.present?
    if @user.save
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      render :new
    end
  end

  def login
    if request.post?
      if (user = User.authenticate(params[:email], params[:password])).present?
        session[:user_id] = user.id
        redirect_to root_path
      else
        flash[:notice] = I18n.t(:email_or_password_invalid)
        render :login
      end
      return
    end
    redirect_to root_path if current_user.present?
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  标题：<%= f.text_field :title %><br />
  正文：<%= f.text_area :body %><br />

  <% Tag.all.each do |tag| %>
    <label for="tag_<%= tag.id %>"><%= tag.name %></label>
    <input type='checkbox' name='tag_ids[]' value="<%= tag.id %>" <%= @article.tags.include?(tag) ? 'checked': '' %>/>
  <% end %>
  <br />
  <%= f.submit('提交') %>
<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<%= paginate @articles if @articles %>
<p><%= link_to '新建', new_article_path %></p>
<div>
	<ul>
		<% @articles && @articles.each do |article| %>
		<li>
			<h1><%=link_to article.title, article_path(article) %></h1>
			<p><%= link_to '编辑', edit_article_path(article) %></p>
			<p><%= article.body.truncate(100) %></p>
			<p>
				<%= article.tags.map(&:name).join(' ') %>
			</p>
			<div>
				<p><h3>最新评论:</h3></p>
				<% article.comments.includes(:user).order('id DESC').limit(3).each do |comment| %>
					<p><i>--<%= comment.user.name %>--</i></p>
					<p><%= comment.body %></p>
				<% end %>
			</div>
		</li>
		<% end %>
	</ul>
</div>
<%= paginate @articles if @articles %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
	标题：<%= f.text_field :title %><br />
	正文：<%= f.text_area :body %><br />
	<%= f.submit('提交') %>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.body %></p>
<p>评论(<span class='comment_count'><%= @article.comments.count %></span>)</p>
<%= form_for Comment.new, remote: true do |f| %>
	<%= hidden_field_tag :commentable_id, @article.id %>
	<%= hidden_field_tag :commentable_type, 'Article' %>
	<%= f.text_area :body %><br />
	<%= f.submit('提交评论') %>
<% end %>
<%= paginate @comments %>
<ul>
	<% @comments.each do |comment| %>
		<li>
			<p><i><%= comment.user.name %></i></p>
			<p><%= comment.body %></p>
		</li>
	<% end %>
</ul>
<%= paginate @comments %>

<script type="text/javascript">
	$(function(){
		$('form').submit(function(){
			$(this).ajaxSubmit(function(data){
				if(data.code == 'success'){
					var comment_count = parseInt($(".comment_count").text()) + 1
					$(".comment_count").text(comment_count);
				}
				var li = $("<li></li>")
				li.append("<p><i>" + data.data.name + "</i></p>")
				li.append("<p>" + data.data.body + "</p>")
				$("ul").prepend(li)
				if($('ul li').length > 5){
					$("ul li:last").remove()
				}
			});
			return false
		})
	})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lhy Blog</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="imagetoolbar" content="false" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="minimal-ui, width=device-width, initial-scale=1.0, user-scalable=no">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track' => false %>
  <%= yield :head %>
  <%= csrf_meta_tags %> 
</head>
<body>
  <%= render partial: 'layouts/shares/top' %>
  <%= yield %>
</body>
</html>

app/views/layouts/shares/_top.html.erb
<div>
  <p style="text-align: right;">
    <% if current_user.present? %>
      <%= link_to '退出', logout_path %>
      <% if current_user.post.present? %>
        <%= link_to '我的博客', post_path(current_user.post) %>
      	<%= link_to '我的文章', articles_path %>
      <% else %>
      	<%= link_to '开通博客', new_post_path %>
      <% end %>
    <% else %>
      <%= link_to '登陆', login_path %>
    <% end %>
  </p>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  标题：<%= f.text_field :title %><br />
  介绍：<%= f.text_area :body %><br />

  <% Tag.all.each do |tag| %>
    <label for="tag_<%= tag.id %>"><%= tag.name %></label>
    <input type='checkbox' name='tag_ids[]' value="<%= tag.id %>" <%= @post.tags.include?(tag) ? 'checked': '' %>/>
  <% end %>
  <br />
  <%= f.submit('提交') %>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<%= paginate @posts if @posts %>
<div>
	<ul>
		<% @posts && @posts.each do |post| %>
		<li>
			<h1><%= link_to post.title, post_path(post) %></h1>
			<p><%= post.tags.map(&:name).join(' ') %></p>
			<p><%= post.body.truncate(100) %></p>
			<div>
				<p><h3>最新评论:</h3></p>
				<% post.comments.includes(:user).order('id DESC').limit(3).each do |comment| %>
					<p><i>--<%= comment.user.name %>--</i></p>
					<p><%= comment.body %></p>
				<% end %>
			</div>
		</li>
		<% end %>
	</ul>
</div>
<%= paginate @posts if @posts %>

app/views/posts/new.html.erb
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.tags.map(&:name).join(' ') %></p>
<p><%= link_to '编辑', edit_post_path(@post) %></p>
<p><%= @post.body %></p>
<p>评论(<span class='comment_count'><%= @post.comments.count %></span>)</p>
<%= form_for Comment.new, remote: true do |f| %>
	<%= hidden_field_tag :commentable_id, @post.id %>
	<%= hidden_field_tag :commentable_type, 'Post' %>
	<%= f.text_area :body %><br />
	<%= f.submit('提交评论') %>
<% end %>
<%= paginate @comments %>
<ul>
	<% @comments.each do |comment| %>
		<li>
			<p><i><%= comment.user.name %></i></p>
			<p><%= comment.body %></p>
		</li>
	<% end %>
</ul>
<%= paginate @comments %>

<script type="text/javascript">
	$(function(){
		$('form').submit(function(){
			$(this).ajaxSubmit(function(data){
				if(data.code == 'success'){
					var comment_count = parseInt($(".comment_count").text()) + 1
					$(".comment_count").text(comment_count);
				}
				var li = $("<li></li>")
				li.append("<p><i>" + data.data.name + "</i></p>")
				li.append("<p>" + data.data.body + "</p>")
				$("ul").prepend(li)
				if($('ul li').length > 5){
					$("ul li:last").remove()
				}
			});
			return false
		})
	})
</script>

app/views/users/login.html.erb
<%= form_tag login_path, method: :post do %>
  邮箱：<%= text_field_tag :email %><br />
  密码：<%= password_field_tag :password %><br />
  <%= submit_tag('登陆') %>
<% end %>
<p><%= link_to '注册', new_user_path %></p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @user, method: :post do |f| %>
  邮箱：<%= f.text_field :email %><br />
  密码：<%= f.password_field :password %><br />
  确认密码：<%= f.password_field :password_confirmation %><br />
  <%= f.submit('注册') %>
<% end %>
<p><%= link_to '登陆', login_path %></p>